image: debian:testing-slim

stages:
  - build
  - test
  - coverage
  - static-analysis

before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc sed clang-tools lcov libjansson-dev libjson-c-dev libcjson-dev valgrind flawfinder pkg-config git

build:
  script: make
  artifacts:
    paths:
      - mustach
      - libmustach*.so*

gcov:
  stage: coverage
  script:
    - CFLAGS='-Wall -O0 --coverage' LDFLAGS='-Wl,-z,noexecstack --coverage' make -B
    - CFLAGS='-Wall -O0 --coverage' LDFLAGS='-Wl,-z,noexecstack --coverage' make test
    - lcov --capture --directory . --output-file coverage.info
    - genhtml coverage.info --output-directory gcov-latest
  artifacts:
    paths:
      - gcov-latest

scan-build:
  stage: static-analysis
  script:
    - scan-build make
  after_script:
    - cp -R /tmp/scan-build-* scan-build-latest
  artifacts:
    paths:
      - scan-build-latest

flawfinder:
  stage: static-analysis
  script:
    - flawfinder --error-level=5 .

test:
  script:
    - make -B tool=jsonc libs=none test

