name: Merge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-action@v1
      - uses: rekgrpth/git-fetch-upstream-action@v1
        with:
          repository: jobol/mustach
          url: https://gitlab.com/
      - uses: rekgrpth/git-merge-upstream-action@v1
      - uses: rekgrpth/git-push-action@v1
