on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: rekgrpth/merge-upstream@v2
        with:
          repository: 'git@gitlab.com:'
          upstream: jobol/mustach
